// REDUX ACTION TYPES

export const GETCONTACTSSTART: string = "GETCONTACTSSTART";
export const GETCONTACTSSUCSESS: string = "GETCONTACTSSUCSESS";
export const GETCONTACTSERROR: string = "GETCONTACTSERROR";

export const POSTCONTACTSSTART: string = "POSTCONTACTSSTART";
export const POSTCONTACTSSUCSESS: string = "POSTCONTACTSSUCSESS";
export const POSTCONTACTSERROR: string = "POSTCONTACTSERROR";

export const DELETECONTACTSSTART: string = "DELETECONTACTSSTART";
export const DELETECONTACTSSUCSESS: string = "DELETECONTACTSSUCSESS";
export const DELETECONTACTSERROR: string = "DELETECONTACTSERROR";
